# Generated by Django 5.0 on 2023-12-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_to', models.CharField(max_length=250)),
                ('assign_by', models.CharField(max_length=250)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('username', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
