# Generated by Django 5.0 on 2023-12-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installer', '0003_alter_message_chat_alter_message_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='participants',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
