# Generated by Django 5.0 on 2023-12-07 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installer', '0004_remove_chat_participants_delete_message_delete_chat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Task',
        ),
    ]
