# Generated by Django 5.0 on 2023-12-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installer', '0006_product_transaction_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='email',
        ),
        migrations.RemoveField(
            model_name='task',
            name='username',
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
