# Generated by Django 5.0 on 2023-12-10 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installer', '0007_remove_task_email_remove_task_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
    ]
